var MAIN_SHEET='Báo Cáo Tổng Hợp';var SESSION_SHEET='Nhật ký phiên';var CHARACTER_COUNT=1;
function doGet(){return out_({success:true,service:'history-report-trung-trac-v1'})}
function doPost(e){var lock=LockService.getScriptLock();try{lock.waitLock(10000);var d=JSON.parse((e&&e.postData&&e.postData.contents)||'{}');var ss=SpreadsheetApp.getActiveSpreadsheet();var main=ensureMain_(ss),sessions=ensureSessions_(ss);if(String(d.eventType||'interaction')==='session_summary'){appendSession_(sessions,d);updateSessionStats_(main,d)}else{appendInteraction_(main,d);updateAiStats_(main,d)}return out_({success:true})}catch(err){return out_({success:false,message:String(err)})}finally{try{lock.releaseLock()}catch(_){}}}
function ensureMain_(ss){var s=ss.getSheetByName(MAIN_SHEET)||ss.insertSheet(MAIN_SHEET);if(s.getLastRow()===0){s.getRange('A1:E1').merge().setValue('BẢO TÀNG LỊCH SỬ SỐ TƯƠNG TÁC');s.getRange('A2:E2').setValues([['TỔNG THỜI GIAN THỰC','TỔNG PHIÊN HỌC','NHÂN VẬT','TỔNG LƯỢT TƯƠNG TÁC AI','']]);s.getRange('D2:E2').merge();s.getRange('A3:E3').setValues([['00:00:00',0,CHARACTER_COUNT,0,'']]);s.getRange('D3:E3').merge();s.getRange('A4:E4').setValues([['THỜI GIAN','HỌ TÊN HỌC SINH','NHÂN VẬT KHÁM PHÁ','CHỨC NĂNG','NỘI DUNG TƯƠNG TÁC']])}s.getRange('C3').setValue(CHARACTER_COUNT);s.setFrozenRows(4);s.setColumnWidth(1,165);s.setColumnWidth(2,180);s.setColumnWidth(3,165);s.setColumnWidth(4,180);s.setColumnWidth(5,650);s.getRange('A1:E1').setFontWeight('bold').setHorizontalAlignment('center').setBackground('#efe3ca').setFontColor('#71352f');s.getRange('A2:E2').setFontWeight('bold').setBackground('#fef3c7').setHorizontalAlignment('center').setWrap(true);s.getRange('A4:E4').setFontWeight('bold').setFontColor('white').setBackground('#426b8f').setHorizontalAlignment('center');return s}
function ensureSessions_(ss){var s=ss.getSheetByName(SESSION_SHEET)||ss.insertSheet(SESSION_SHEET);if(s.getLastRow()===0){s.getRange(1,1,1,12).setValues([['THỜI GIAN KẾT THÚC','SESSION ID NỘI BỘ','HỌ TÊN','NHÂN VẬT','NGÔN NGỮ','THỜI GIAN (GIÂY)','TRA CỨU','GIẢ ĐỊNH','NHẬP VAI','TIẾN TRÌNH','CÂU HỎI / CHỦ ĐỀ','LÝ DO KẾT THÚC']]);s.getRange(1,1,1,12).setFontWeight('bold').setBackground('#345b79').setFontColor('white');s.setFrozenRows(1)}return s}
function appendInteraction_(s,d){var h=Array.isArray(d.history)?d.history:[],lines=['SESSION NỘI BỘ: '+String(d.sessionId||''),'NGÔN NGỮ: '+String(d.lang||'vi')];for(var i=0;i<h.length;i++){var it=h[i]||{};lines.push((it.role==='user'?'CÂU HỎI / QUYẾT ĐỊNH:':'PHẢN HỒI:')+'\n'+String(it.content||''))}var row=[Utilities.formatDate(new Date(),'GMT+7','HH:mm:ss - dd/MM/yyyy'),String(d.playerName||'Người học'),String(d.character||'Trưng Trắc'),String(d.type||'Tương tác'),lines.join('\n\n-----------------------------------\n\n')];s.appendRow(row);var r=s.getLastRow();s.getRange(r,1,1,5).setWrap(true).setVerticalAlignment('top')}
function appendSession_(s,d){var m=d.metadata||{},j=m.journey||{};var jt=Object.keys(j).map(function(k){return k+': '+(j[k]?'xong':'chưa')}).join(' | ');s.appendRow([Utilities.formatDate(new Date(),'GMT+7','HH:mm:ss - dd/MM/yyyy'),String(d.sessionId||''),String(d.playerName||'Người học'),String(d.character||''),String(d.lang||'vi'),Number(m.durationSeconds||0),Number(m.qaCount||0),Number(m.whatifCount||0),Number(m.roleplayCount||0),jt,(Array.isArray(m.questions)?m.questions.join('\n• '):''),String(m.reason||'user-finish')])}
function updateAiStats_(s,d){var p=PropertiesService.getScriptProperties(),v=Number(p.getProperty('total_ai_uses')||0)+1;p.setProperty('total_ai_uses',String(v));s.getRange('D3').setValue(v)}
function updateSessionStats_(s,d){var p=PropertiesService.getScriptProperties(),sec=Number(p.getProperty('total_time_seconds')||0)+Number((d.metadata||{}).durationSeconds||0),cnt=Number(p.getProperty('total_sessions')||0)+1;p.setProperty('total_time_seconds',String(sec));p.setProperty('total_sessions',String(cnt));s.getRange('A3').setValue(fmt_(sec));s.getRange('B3').setValue(cnt);s.getRange('C3').setValue(CHARACTER_COUNT)}
function fmt_(sec){sec=Math.floor(Math.max(0,sec));var h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),x=sec%60;return pad_(h)+':'+pad_(m)+':'+pad_(x)}function pad_(n){return n<10?'0'+n:String(n)}function out_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function synchronizeDashboard(){var ss=SpreadsheetApp.getActiveSpreadsheet();ensureMain_(ss);ensureSessions_(ss)}
function autoDeleteOldData(){console.log('Đã vô hiệu hóa để bảo toàn dữ liệu nghiên cứu cũ.')}
function testWriteSampleData(){var id='test-'+Utilities.getUuid().slice(0,8);doPost({postData:{contents:JSON.stringify({eventType:'interaction',sessionId:id,playerName:'HỌC SINH THỬ',character:'Trưng Trắc',type:'Tra cứu sử liệu',lang:'vi',history:[{role:'user',content:'Trưng Trắc xưng vương trong bối cảnh nào?'},{role:'assistant',content:'Dòng dữ liệu kiểm tra.'}]})}});doPost({postData:{contents:JSON.stringify({eventType:'session_summary',sessionId:id,playerName:'HỌC SINH THỬ',character:'Trưng Trắc',lang:'vi',metadata:{durationSeconds:125,qaCount:1,whatifCount:0,roleplayCount:0,journey:{artifact:true,profile:true,qa:true,whatif:false,role:false},questions:['Trưng Trắc xưng vương trong bối cảnh nào?'],reason:'manual-test'}})}});SpreadsheetApp.getActive().toast('Đã ghi dữ liệu thử.','Kiểm tra',6)}
